### ISSUE TITLE
Latest release looks incompatible with Java 8

### ISSUE THREAD

**Issue by don-vip** [matsim-org/josm-matsim-plugin#105]
Hello,
We require that plugins listed in default JOSM list to be compatible with lowest version of Java supported by JOSM (currently 8), unless they target a more recent version by specifying `Plugin-Minimum-Java-Version`.
The latest version of matsim plugin triggered a [lot of warnings](https://josm.openstreetmap.de/jenkins/job/JOSM-Integration/3307/warnings3Result/) suggesting it has been built with a more recent version, and thus will not run correctly on Java 8.
If that's effectively the case, can you please reissue the plugin compiled with a JDK8?

**Comment by nkuehnel** [comment]
Oops yes, will have a look in the next week

**Comment by nkuehnel** [comment]
@don-vip 
I just released a new version and updated it on the josm plugins source site. Could you please check if it works now?

**Comment by don-vip** [comment]
The warnings are gone but someone created a bug report for this plugin: https://josm.openstreetmap.de/ticket/17873

**Comment by politogroup20** [comment]
this bug is posted by me it still not working and exporting shape file

**Comment by don-vip** [comment]
This can be addressed by https://github.com/matsim-org/josm-matsim-plugin/issues/107. My issue is fixed :)
